config/routes.rb
Rails.application.routes.draw do

  root 'lessons#main'
  get 'lessons/materials', to: 'lessons#materials', as: 'materials_lesson'
  get 'lessons/quiz', to: 'lessons#quiz', as: 'quiz_lesson'
  get 'lessons/dragndrop', to: 'lessons#dragndrop', as: 'dragndrop_lesson'
  get 'lessons/raspi', to: 'lessons#raspi', as: 'raspi_lesson'
  get 'lessons/setup', to: 'lessons#setup', as: 'setup_lesson'
  get 'lessons/code', to: 'lessons#code', as: 'code_lesson'
  get 'lessons/html', to: 'lessons#html', as: 'html_lesson'
  get 'lessons/tweetmonitor', to: 'lessons#tweetmonitor', as: 'tweetmonitor_lesson'
  get 'lessons/tweetmonitor2', to: 'lessons#tweetmonitor2', as: 'tweetmonitor2_lesson'
  get 'lessons/tweetmonitor3', to: 'lessons#tweetmonitor3', as: 'tweetmonitor3_lesson'

  get 'leaderboard', to: 'lessons#leaderboard', as: 'leaderboard'

  get 'forum', to: 'questions#index', as: 'forum_questions'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  post '/update_score', to: 'users#update_score'
  get 'tags/:tag', to: 'questions#index', as: :tag

  resources :questions do
    resources :answers do
      post 'upvote'
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes, dependent: :destroy
  validates :response, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true

  def self.tagged_with(name)
    Tag.find_by_name!(name).questions
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name,count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

    def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
      end
    end

    def self.search(search)
    where("title ilike :search or description ilike :search or tags.name ilike :search ", {:search => "%#{search}%" })
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :questions, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :questions
  has_many :answers
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def create
    @answer = current_user.answers.new(answer_params)
    @question = Question.find(params[:question_id])
    @question.answers << @answer
    if @answer.save
      redirect_to question_path(@question), notice:"Your answer #{@answer.response} for this question was saved"
    else
      @errors = @answer.errors
      render '/answers/new'
    end
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:question_id])
      if @answer.update(answer_params)
        redirect_to question_path(@answer.question_id), notice:"Your answer #{@answer.response} was successfully updated"
      else
         redirect_to "/answers/show"
      end
  end

  def upvote
    @answer = Answer.find(params[:answer_id])
    @answer.votes.create
    redirect_to(question_path(@answer.question))
  end

  private
  def answer_params
    params.require(:answer).permit(:response, :question_id, :user_id)
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def dragndrop
  end

  def quiz
  end

  def materials
  end

  def setup
  end

  def raspi
  end

  def main
  end

  def code
  end

  def html
  end

  def leaderboard
    @users = User.all.sort{ |x, y| y.score <=> x.score }
  end

  def tweetmonitor
  end

  def tweetmonitor2
  end

  def tweetmonitor3
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # def index
  #   @questions = Question.all
  #   if params[:search]
  #   @questions = Question.search(params[:search]).order("created_at DESC")
  #   else
  #   @questions = Question.all.order('created_at DESC')
  #   end
  # end

   def index
    @questions = Question.all
    if params[:search]
      @questions = Question.joins(:tags).search(params[:search]).order("created_at DESC").uniq
    elsif params[:tag]
      @questions = Question.tagged_with(params[:tag])
      @user = current_user
    else
      @questions = Question.order('created_at DESC')
      @user = current_user
    end
  end

  # def index
  #   if params[:tag]
  #     @questions = Question.tagged_with(params[:tag])
  #     @user = current_user
  #   else
  #     @questions = Question.all
  #     @user = current_user
  #   end
  # end

  def new
    @question = Question.new
  end


  def edit
    @question = Question.find(params[:id])
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to question_path(@question.id), notice:"your question #{@question.title} was sucessfully created"
    else
      @errors = @question.errors
      render '/questions/new'
    end
  end


  def update
    @question = Question.find(params[:id])
      if @question.update(question_params)
        redirect_to question_path(@question.id), notice:"Your answer #{@question.description} was sucessfully updated"
      else
         redirect_to "/answers/show"
      end
  end

  def destroy
    @question = Question.find(params[:id]).destroy
    redirect_to '/questions',
    notice:"your question was sucessfully deleted"
  end

   private
    def question_params
     params.require(:question).permit(:title, :description, :user_id, :tag_list)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end


  def update_score
    score = params[:score]
    score_int = Integer(score)
    current_user.score += score_int
    current_user.save
    render :nothing => true
  end

  def create
    user = User.new(user_params)
    user.score = 0
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / Integer(max.count) * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/edit.html.erb
<div class="panel panel-info new-question">
  <div class="panel-heading">
    <h2 class="panel-title"><strong>Edit your answer</strong></h2>
  </div>
  <div class="panel-body">
    <%= form_for [@question, @answer], class: "form-horizontal" do |f| %>

    <div class="form-group">
      <label for="title" class="col-lg-2 control-label">Response</label>
      <div class="col-lg-10">
        <%= f.text_field :response ,class: "form-control"%>
      </div>
    </div>

    <%= button_tag class: "btn btn-material-pink btn-raised pull-right" do %>
        Edit your answer
      <div class="ripple-wrapper">
      </div>
    <% end %>
  </div>
  <% end %>
</div>

<div style="font-size: 22px;">
  <div class="container">
    <%= link_to "", questions_path, class: 'mdi-navigation-chevron-left', style: "font-size: 65px; padding-left: 15px;" %>
</div>

app/views/answers/show.html.erb
<h1> Answer replied to</h1>
<h2> Question </h2>
<% @question = Question.find(@answers.question_id) %>
<%= @question.title %>
<p>
<h2> Answer </h2>
<%= @answer.response %>
<p>
<p>
<%= link_to 'reply', new_answer_path %>
<%= link_to 'edit answer', edit_answer_path %>
</p>
</p>

app/views/lessons/dragndrop.html.erb
  <div class='container'>
    <div id="shareCon">
      <div class="alert alert-dismissable alert-material-pink">
        <button type="button" class="close" data-dismiss="alert">X</button>
        <strong><p class="congrats">Well Done!</p></strong></a>
        <p id="share">It took you 00 attempts to build your Pi.</p>
        <%= link_to 'Back', raspi_lesson_path, class: 'btn btn-info btn-raised back dragndrop' %>
        <%= link_to 'Next', materials_lesson_path, class: 'btn btn-success btn-raised next dragndrop' %>
      </div>
    </div>
    <div class="panel panel-material-pink dragndrop">
      <div class="panel-heading">
        <h3 class="panel-title" style="text-align: center; font-size: 24px;">Build your Raspberry Pi</h3>
      </div>
      <div class="panel-body dragndrop">
        <div id="scoreCon">
          <div class="instruct">Drag the parts below their corresponding places below.</div>
          <ul class="nav nav-pills count dragndrop">
            <li>
              <div class="score">Correct: <span class="badge" class="numDisp" id="numCorrect">0</span></div>
            </li>
            <li>
              <div class="score"> Attempts: <span class="badge" class="numDisp" id="numAttempts">0</span></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div style="clear:both"></div>
    <div id="detail">
      <div id="detailCon">
        <div id="closebtn">X</div>
        <div id="photoCon"></div>
        <div id="desc"></div>
      </div>
    </div>
  </div>
  <!--DRAGGABLE THINGS-->
  <!--   <div class="panel panel-default">
    <div class="panel-body"> -->
  <div id="partsCon1" class="container" style="width: 65%">
    <div class="row">
      <div class="col-md-offset-1 col-md-1">
        <div class="individualpart draggable" id="hdmi">
        <%= image_tag('hdmi.png') %>
        </div>
      </div>
      <div class="col-md-offset-1 col-md-1">
        <div class="individualpart draggable" id="cameracsi">
          <%= image_tag('cameracsi.png') %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="individualpart draggable" id="cpugpu">
          <%= image_tag('cpugpu.png') %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="individualpart draggable" id="displaydsi">
          <%= image_tag('displaydsi.png') %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="individualpart draggable" id="ethernet">
          <%= image_tag('ethernet.png') %>
        </div>
      </div>
    </div>
    <div row="row">
      <div class="col-md-offset-1 col-md-1">
        <div class="individualpart draggable" id="usb2">
          <%= image_tag('usb2.png') %>
        </div>
      </div>
      <div class="col-md-offset-2 col-md-1">
        <div class="individualpart draggable" id="usbethernetcontroller">
          <%= image_tag('controller.png') %>
        </div>
      </div>
      <div class="col-md-offset-1 col-md-1">
        <div class="individualpart draggable" id="videoaudio">
          <%= image_tag('videoaudio.png') %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="individualpart draggable" id="microusb">
          <%= image_tag('microusb.png') %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="individualpart draggable" id="usb">
          <%= image_tag('usb.png') %>
        </div>
      </div>
    </div>
  </div>
  <!--END DRAGGABLE THINGS-->
  <div style="clear:both"></div>
  <div id="detail">
    <div id="detailCon">
      <div id="closebtn">X</div>
      <div id="photoCon"></div>
      <div id="desc"></div>
    </div>
  </div>
  <!--DROP TARGETS-->
  <div class="container" id="pi">
    <div class="droppable" id="usb" data-id="0">
      <%= image_tag('usbempty.png') %>
    </div>
    <div class="droppable" id="usb2" data-id="1">
      <%= image_tag('usbempty.png') %>
    </div>
    <div class="droppable" id="ethernet" data-id="2">
      <%= image_tag('ethernetempty.png') %>
    </div>
    <div class="droppable" id="usbethernetcontroller" data-id="3">
      <%= image_tag('controllerempty.png') %>
    </div>
    <div class="droppable" id="videoaudio" data-id="4">
      <%= image_tag('videoaudioempty.png') %>
    </div>
    <div class="droppable" id="cameracsi" data-id="5">
      <%= image_tag('cameracsiempty.png') %>
    </div>
    <div class="droppable" id="cpugpu" data-id="6">
      <%= image_tag('cpugpuempty.png') %>
    </div>
    <div class="droppable" id="hdmi" data-id="7">
      <%= image_tag('hdmiempty.png') %>
    </div>
    <div class="droppable" id="microusb" data-id="8">
      <%= image_tag('microusbempty.png') %>
    </div>
    <div class="droppable" id="displaydsi" data-id="9">
      <%= image_tag('displaydsiempty.png') %>
    </div>
      <%= image_tag('raspberrypi.png') %>
  </div>
  <!--END DROP TARGETS-->

app/views/lessons/html.html.erb
  <div class="panel panel-material-pink video">
    <div class="panel-heading video">
      <h3 class="panel-title" style="text-align: center; font-size: 24px;">Why Learn HTML?</h3>
    </div>
    <div class="panel-body video">
      <div class="html image">
      <%= image_tag('htmlcss.png') %>
      </div>
      <hr>
      <p class="video">Every webpage you look at is written in a language called HTML.</p>
      <p class="video"><strong>HTML</strong> stands for HyperText Markup Language. A markup language is a programming language used to make text do more than just sit on a page: it can turn text into images, links, tables, lists, and much more. HTML is the markup language we'll be learning.</p>
      <p class="video"><strong>CSS</strong> is what makes webpages pretty. CSS means Cascading Style Sheets. Think of it like skin and makeup that covers the bones of HTML.</p>
      <br>
      <p class="video">Now let's get started!
      <hr>
      <%= link_to 'Back', root_path, class: 'btn btn-info back video' %>
      <%= link_to 'Next', quiz_lesson_path, class: 'btn btn-success next video' %>
    </div>
  </div>

app/views/lessons/main.html.erb
  <!-- START TILES-->
  <div class="dashboard display-animation" style="margin: 0 auto; width: 1130px;">
    <a class="tile tile-lg tile-pink ripple-effect" href="<%= raspi_lesson_path %>">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img raspi" style="height: 89%; width: 127%; margin-left: -76px; background-image: url(http://i.imgur.com/NgRPsh7.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Make your own Computer using Raspberry Pi</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-sqr tile-purple ripple-effect" href="#">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img" style="height: 101%; width: 145%; margin-left: -40px; background-image: url(http://i.imgur.com/zfUHPHs.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Women in Tech</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-sqr tile-cyan ripple-effect" href="<%= forum_questions_path %>">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img forum" style="height: 124%; width: 145%; margin-left: -43px; background-image: url(http://i.imgur.com/QCE6Hth.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Forum</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-sqr tile-amber ripple-effect" href="#">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img tile-img-bg grace" style="height: 93%; margin-top: 39px; width: 133%; margin-left: 22px; background-size: 60%; background-image: url(http://i.imgur.com/yZ4dUea.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">About Amazing Grace</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-light-blue ripple-effect" href="<%= html_lesson_path %>">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img tile-img-bg" style="height: 95%; margin-left: 85px; width: 72%; margin-top: 1px; background-image: url(http://i.imgur.com/Z5ZP1wv.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Create a Website using HTML and CSS</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-sqr tile-red ripple-effect" href="<%= leaderboard_path %>">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img leaderboard" style="height: 176%; margin-top: -39px; width: 115%; margin-left: 15px; background-image: url(http://i.imgur.com/SegPOgi.png); background-size: 90%, 90%;"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Leaderboard</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-sqr tile-indigo ripple-effect" href="#">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img" style="height: 109%; margin-left: 29px; background-image: url(http://i.imgur.com/QuqFS1V.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Animate your Webpages using JavaScript</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-sqr tile-deep-orange ripple-effect" href="#">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img" style="margin-left: 22px; margin-top: 23px; background-image: url(http://i.imgur.com/5M6JVm6.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Create a Web App using Ruby on Rails</span>
      </span>
      </span>
      </span>
    </a>
    <a class="tile tile-lg tile-light-green ripple-effect" href="<%= tweetmonitor_lesson_path%>">
      <span class="content-wrapper">
      <span class="tile-content">
        <span class="tile-img tile-img-bg" style="margin-top: -165px; height: 153%; background-image: url(http://i.imgur.com/BgL7jRB.png);"></span>
      <span class="tile-holder tile-holder-sm">
          <span class="title">Create a Twitter Monitor using Raspberry Pi</span>
      </span>
      </span>
      </span>
    </a>
  </div>
  <!-- TILES END-->

app/views/lessons/materials.html.erb
  <div class="panel panel-material-pink checklist">
    <div class="panel-heading checklist">
      <h3 class="panel-title" style="text-align: center; font-size: 24px;">Materials Needed<br>for<br>Raspberry Pi Setup</h3>
    </div>
    <div class="panel-body checklist">
        <p class="video">
          <input id="question1" name="question1" type="checkbox" value="1">
          <label>SD Card</label>
          <p class="video">We recommend an 8GB class 4 SD card – ideally <a class="video" href="http://swag.raspberrypi.org/collections/frontpage/products/noobs-8gb-sd-card"
            target="_blank">preinstalled</a> with NOOBS. You can buy a card with
            NOOBS pre-installed, or you can download it for free from our <a class="video" href="https://www.raspberrypi.org/downloads/"
            target="_blank">downloads</a> page.</p>
        </p>
        <p class="video">
          <input id="question2" name="question2" type="checkbox" value="1">
          <label><strong>Display and connectivity cables</strong></label>
          <p class="video">Any HDMI/DVI monitor or TV should work as a display for the Pi . For best
            results, use one with HDMI input, but other connections are available
            for older devices. Use a standard Ethernet cable for internet access.</p>
        </p>
        <p class="video">
          <input id="question3" name="question3" type="checkbox" value="1">
          <label><strong>Keyboard and mouse</strong></label>
          <p class="video">Any standard USB keyboard and mouse will work with your Raspberry Pi.</p>
        </p>
        <p class="video">
          <input id="question4" name="question4" type="checkbox" value="1">
          <label> <strong>Power Supply</strong></label>
          <p class="video">Use a 5V micro USB power supply to power your Raspberry Pi. Be careful
            that whatever power supply you use outputs at least 5V; insufficient
            power will cause your Pi to behave in strange ways.</p>
        </p>
        <hr />
        <a href="<%= dragndrop_lesson_path %>" class="btn btn-info back">Back</a>
        <a href="<%= setup_lesson_path %>" class="next checklist"><input class="btn btn-success next_button checklist" name="commit" type="submit" value="Next" disabled=""></a>
      </form>
    </div>
  </div>

app/views/lessons/quiz.html.erb
<div style="padding: 45px 50px;" id='quiz-container'>
  <script>
  $('#quiz-container').jquizzy({
    questions: init.questions,
    resultComments: init.resultComments,
    message: "Hi!"
  });
  </script>
</div>

app/views/lessons/raspi.html.erb
  <div class="panel panel-material-pink video">
    <div class="panel-heading video">
      <h3 class="panel-title" style="text-align: center; font-size: 24px;">What is a Raspberry Pi?</h3>
    </div>
    <div class="panel-body video">
      <iframe width="560" height="315" style="margin-left: 23px;" src="https://www.youtube.com/embed/uXUjwk2-qx4"
      frameborder="0" allowfullscreen></iframe>
      <hr>
      <p class="video">The <strong>Raspberry Pi</strong> is a low cost, credit-card sized, <strong>computer</strong> that plugs into a computer monitor or TV and uses a standard keyboard and
        mouse.
      <p class="video">It’s capable of doing everything you’d expect a desktop computer to do: From
        browsing the internet and playing high-definition video, to making spreadsheets,
        word-processing, and playing games.</p>
      <p class="video">The Raspberry Pi has the ability to interact with the outside world and
        has been used in a wide array of projects: From music machines and parent
        detectors to weather stations and tweeting birdhouses with infrared
        cameras.</p>
      <br>
      <hr>
      <%= link_to 'Back', root_path, class: 'btn btn-info back video' %>
      <%= link_to 'Next', dragndrop_lesson_path, class: 'btn btn-success next video' %>
    </div>
  </div>

app/views/questions/index.html.erb
<div style="font-size: 18px;">
  <div class="container">
  <%= link_to "", root_path, class: 'mdi-navigation-chevron-left', style: "font-size: 65px; padding-left: 39px;" %>
  </div>

  <!-- this is showing the most popular tags -->

  <div class="container">
    <div class="row">

  <!-- this is the search feature -->
      <div class="col-md-6 col-md-offset-6">
        <%= form_tag(forum_questions_path, method: "get") do %>
        <%= label_tag :search, "", style: "padding-left: 97px;" %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag "Search", class: "btn btn-success btn-raised"  %>
        <% end %>
       </div>
    </div>
  </div>
  </div>


  <div class="container">
  <div class="panel panel-material-pink" style="margin-left: 89px; width: 85%">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-11">
          <h1 style="text-align: center;">Questions</h1>
        </div>
        <div class="col-md-1" style="margin-top: 17px;">
          <% if current_user %>
            <%= link_to '', new_question_path, class: 'mdi-content-add-circle-outline', style: "font-size: 40px; color: white;" %>
          <% end %>
        </div>
      </div>
    </div>

    <% @questions.each do |question| %>
    <ul style="list-style-type: none; padding-top: 20px;">
      <div class="row">
        <li>
          <div class="col-md-9">
            <%= image_tag avatar_url(question.user, 35), class: "avatargravatar" %> <%=  question.user.name.split.map(&:capitalize).join(' ') %> - <%= time_ago_in_words(question.created_at) %> ago
            <h3><%= link_to question.title, question_path(question.id) %></h3>
            <p>Description: <%= link_to question.description, question_path(question.id) %></p>
          </div>
          <div class="col-md-3">
            Tags: <%= raw question.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
          </div>
        </li>
      </div>
      <hr />

    </ul>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div style="font-size: 22px;">
  <div class="container">
    <%= link_to "", questions_path, class: 'mdi-navigation-chevron-left', style: "font-size: 65px; padding-left: 15px;" %>
</div>

<div class="well show-question">
  <ul style="list-style-type: none; padding-top: 20px;">
    <li>
        <h2><strong>Question</strong></h2>
        <% if @question.user == current_user %>
          <h5><%= link_to 'Edit', edit_question_path %>
         <%= link_to 'Delete', @question, method: "delete" %></h5>
        <% end %>
        <p><strong><h5>Added by <%= @question.user.name%></h5></strong></p>
        <h4><strong> Title </strong></h4>
          <h5><%= @question.title %></h5>
        <h4><strong> Description </strong></h4>
          <h5><%= @question.description %></h5>
        <h4><strong> Tags </strong></h4>
          <h5><%= raw @question.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></h5>
        <hr class="questions-answers-hr">
        <h2><strong> Answers </strong></h2>

    </li>
  </ul>
  <ul style="list-style-type: none; padding-top: 20px;">
    <%  @question.answers.each do |answer| %>
      <p><strong><h5><%= answer.user.name.capitalize%>'s reply</h5></strong></p>
      <li><h4><%= answer.response %>
        <%= link_to "".html_safe, question_answer_upvote_path(@question,answer), class: "mdi-social-plus-one", method: :post  %></h4>
        <% if answer.user == current_user %>
          <p><h5><%= link_to "Edit", edit_question_answer_path(@question, answer) %></h5></p>
       <% end %>
        <p><h5><%= pluralize(answer.votes.count, "Vote") %></h5></p>
        <hr>
      </li>
    <% end %>
  </ul>
</div>


    <% if current_user %>
    <div class="text-center">
    <%= link_to 'Add a new answer for this question', new_question_answer_path(@question), class: "mdi-content-add" %>
    </div>
    <% end %>

    </div>
    <hr />

    </ul>
  </div>
</div>

</div>